config/routes.rb
Rails.application.routes.draw do

  resources :shipments do
    member do
      get   :data_entry
      patch :save_isolate_data
    end
  end

  root to: "application#index"

  post "specify_hospital_number", to: "specify_hospital_number", controller: :application

  get "/reports/hospital_stats", to: "reports#hospital_stats"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  include SessionHelper

  before_action :assign_body_css_classes

  def index
  end

  def specify_hospital_number
    assign_current_hospital_number
    build_hospital_number_flash_message
    redirect_to action: :index
  end


  private

  def assign_current_hospital_number
    self.current_hospital_number = nil
    if params[:hospital_number].present?
      self.current_hospital_number = params[:hospital_number]
    end
  end

  def build_hospital_number_flash_message
    if current_hospital_number
      flash[:success] = "Hospital number #{current_hospital_number} selected"
    else
      flash[:notice] = "Hospital number cleared"
    end
  end

  def assign_body_css_classes
    @body_css_classes = "#{params[:controller]} #{params[:action]}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.haml
.row
  .col-xs-12
    %h1 Home

.row
  .col-xs-12.col-sm-7
    %h2 Specify hospital

    = form_tag "/specify_hospital_number", class: "form-inline" do
      .form-group
        %label{for: "hospital_number"}
          Enter hospital number
        = text_field_tag "hospital_number", nil, {autofocus: true, class: "form-control"}
      .form-group
        = button_tag "Set", class: "btn btn-primary"

    - if current_hospital_number
      (currently #{current_hospital_number})

  .col-xs-12.col-sm-5
    %h2 Actions
    %p
      = link_to "Enter new shipment", new_shipment_path(hospital_number: current_hospital_number)
    %p
      = link_to "All shipments", shipments_path
    %p
      = link_to "Hospital stats report", "/reports/hospital_stats"