config/routes.rb
Rails.application.routes.draw do

  resources :shipments do
    member do
      get   :data_entry
      patch :save_isolate_data
    end
  end

  root to: "application#index"

  post "specify_hospital_number", to: "specify_hospital_number", controller: :application

  get "/reports/hospital_stats", to: "reports#hospital_stats"

end

app/models/shipment.rb
class Shipment < ApplicationRecord

  has_many :isolates
  accepts_nested_attributes_for :isolates

  validates :hospital_number,  presence: true
  validates :starting_number,  presence: true
  validates :isolate_quantity, presence: true
  validates :objective_code,   presence: true, inclusion: {in: %w(A B Q)}

  before_validation :normalize_objective_code_and_organism


  private

  def normalize_objective_code_and_organism
    if objective_code == "B / H. influenza"
      self.objective_code = "B"
      self.organism = "H. influenza"
    end

    if objective_code == "B / M. catarrhalis"
      self.objective_code = "B"
      self.organism = "M. catarrhalis"
    end
  end

end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController

  def index
    @shipments = Shipment.all.order(id: :desc).paginate(page: params[:page], per_page: 25)
  end

  def show
    @shipment = Shipment.find params[:id]
  end

  def new
    @shipment = Shipment.new hospital_number: params[:hospital_number]
  end

  def create
    @shipment = Shipment.new shipment_params
    if @shipment.save
      flash[:success] = "New shipment record created"
      redirect_to @shipment
    else
      p @shipment.errors
      # TODO: handle failure and error notifictions
    end
  end

  def edit
    @shipment = Shipment.find params[:id]
  end

  def update
    @shipment = Shipment.find params[:id]
    if @shipment.update_attributes shipment_params
      flash[:success] = "Shipment updated"
      redirect_to shipments_path
    else
      flash.now[:failure] = "Some validation errors prevented saving"
      render action: "edit"
    end
  end

  def save_isolate_data
    @shipment = Shipment.find params[:id]
    if @shipment.update_attributes shipment_params
      flash[:success] = "Shipment updated - #{isolate_count_saved} isolate entries saved"
      redirect_to shipments_path
    else
      flash.now[:failure] = "Some validation errors prevented saving"
      render action: "data_entry"
    end
  end

  def data_entry
    @shipment = Shipment.find params[:id]
    build_isolates
  end


  private

  def build_isolates
    required_additional_isolate_records.times do
      @shipment.isolates.build
    end
  end

  def isolate_count_saved
    @shipment.isolates.count
  end

  def required_additional_isolate_records
    total_expected = @shipment.isolate_quantity.to_i
    existing = @shipment.isolates.count
    total_expected - existing
  end

  def shipment_params
    params.require(:shipment).permit!
  end

end

app/helpers/shipment_helper.rb
module ShipmentHelper

  def shipment_objective_codes_with_organisms
    [
      "A",
      "B / H. influenza",
      "B / M. catarrhalis",
      "Q"
    ]
  end

  def selected_shipment_objective_code_with_organism(shipment)
    if shipment.objective_code == "B"
      if shipment.organism.present?
        "#{shipment.objective_code} / #{shipment.organism}"
      end
    else
      shipment.objective_code
    end
  end

end

app/views/shipments/_form.html.haml
= simple_form_for @shipment, wrapper: :vertical_form do |f|

  = f.input :hospital_number

  = f.input :objective_code, as: :select, collection: shipment_objective_codes_with_organisms, selected: selected_shipment_objective_code_with_organism(@shipment)

  = f.input :starting_number, label: "Isolate starting number"

  = f.input :isolate_quantity, label: "Isolate quantity to expect"

  = f.button :submit, value: "Save", class: "btn btn-primary"

app/views/shipments/data_entry.html.haml
%h1 Data entry

%h4
  Shipment ID
  = @shipment.id
  = " :: "
  Hospital
  = @shipment.hospital_number
  = " :: "
  Objective
  = @shipment.objective_code

= simple_form_for @shipment, url: save_isolate_data_shipment_path(@shipment), wrapper: :vertical_form do |f|
  %table.table.table-striped.table-hover.table-condensed.isolate-data-entry
    %thead
      %tr
        - if collect_jmi_number?(@shipment)
          %th
            %small
              JMI#
        %th
          %small
            Code#
        %th
          %small
            Accession#
        %th
          %small
            Organism
        %th
          %small
            Date of
            admission
        %th
          %small
            Date of
            %br
            culture
        - if collect_specimen_type?(@shipment)
          %th
            %small
              Specimen
              %br
              type
        - if collect_bloodstream_infection_source?(@shipment)
          %th
            %small
              Source
        %th
          %small
            Sex
        %th
          %small
            Age
        %th
          %small
            Service
        - if collect_primary_diagnosis?(@shipment)
          %th
            %small
              Primary
              %br
              Diagnosis
        %th
          %small
            ICU?
        %th
          %small
            Nosocomial?

    %tbody
      - idx = 0
      = f.simple_fields_for :isolates do |ff|
        %tr{id: "isolate_form_row_#{idx}"}

          - if collect_jmi_number?(@shipment)
            %td
              = ff.input :jmi_number, label: false, input_html: {maxlength: 100, class: "input-sm"}

          %td
            = ff.input :code_number, label: false, input_html: {maxlength: 100, class: "input-sm"}

          %td
            = ff.input :accession_number, label: false, input_html: {maxlength: 100, class: "input-sm"}

          %td
            = ff.input :organism, label: false, input_html: {maxlength: 100, class: "input-sm"}

          %td.not-too-small
            = ff.input :date_of_admission, as: :string, label: false, input_html: {maxlength: 100, placeholder: "yyyy-mm-dd", class: "input-sm"}

          %td.not-too-small
            = ff.input :date_of_culture, as: :string, label: false, input_html: {maxlength: 100, placeholder: "yyyy-mm-dd", class: "input-sm"}

          - if collect_specimen_type?(@shipment)
            %td.not-too-small
              = ff.input :specimen_type, as: :select, collection: specimen_type_options, label: false, input_html: {class: "input-sm"}

          - if collect_bloodstream_infection_source?(@shipment)
            %td.not-too-small
              = ff.input :source, as: :select, collection: bloodstream_infection_source_options, label: false, input_html: {class: "input-sm"}

          %td.not-too-small
            = ff.input :sex, as: :select, collection: sex_options, label: false, input_html: {class: "input-sm"}

          %td.not-too-small{class: bg_error_class(ff.object, :age)}
            = ff.input :age, label: false, required: false, input_html: {class: "input-sm"}

          %td.not-too-small
            = ff.input :service, as: :select, collection: service_options, label: false, input_html: {class: "input-sm"}

          - if collect_primary_diagnosis?(@shipment)
            %td.not-too-small
              = ff.input :primary_diagnosis, as: :select, collection: primary_diagnosis_options, label: false, input_html: {class: "input-sm"}

          %td.not-too-small{class: bg_error_class(ff.object, :icu)}
            = ff.input :icu, |
              as: :select, |
              include_blank: true, |
              label: false, |
              input_html: {class: "input-sm"}

          %td.not-too-small{class: bg_error_class(ff.object, :nosocomial)}
            = ff.input :nosocomial, |
              as: :select, |
              include_blank: true, |
              label: false, |
              input_html: {class: "input-sm"}
        - idx += 1


  = f.button :submit, value: "Save", class: "btn btn-primary"

app/views/shipments/edit.html.haml
.row
  .col-xs-12.col-sm-offset-1.col-sm-9.col-md-offset-2.col-md-8.col-lg-offset-3.col-lg-6
    %h1
      Edit shipment ID
      = @shipment.id

.row
  .col-xs-12.col-sm-offset-1.col-sm-9.col-md-offset-2.col-md-8.col-lg-offset-3.col-lg-6
    = render partial: "form"

app/views/shipments/index.html.haml
.row
  .col-xs-12
    %h1
      Shipments
      = link_to "+ add new", new_shipment_path(hospital_number: current_hospital_number), class: "btn btn-default btn-sm", alt: "Edit", title: "Edit"

.row
  .col-xs-12
    %table.table.table-striped.table-hover.table-condensed
      %thead
        %tr
          %th
          %th ID
          %th Hospital #
          %th Objective
          %th Starting #
          %th Isolates expected
          %th Isolates entered
      %tbody
        - @shipments.each do |shipment|
          %tr
            %td{class: "edit-shipment-#{shipment.id}"}
              = link_to "Edit", edit_shipment_path(shipment)
            %td
              = link_to shipment.id, shipment

            %td= shipment.hospital_number
            %td= shipment.objective_code
            %td= "#{shipment.objective_code}-#{shipment.starting_number}"
            %td= shipment.isolate_quantity
            %td= shipment.isolates.count

.row
  .col-xs-12
    .center
      = will_paginate @progress_report_requests

app/views/shipments/new.html.haml
.row
  .col-xs-12.col-sm-offset-1.col-sm-9.col-md-offset-2.col-md-8.col-lg-offset-3.col-lg-6
    %h1 New shipment

.row
  .col-xs-12.col-sm-offset-1.col-sm-9.col-md-offset-2.col-md-8.col-lg-offset-3.col-lg-6
    = render partial: "form"

app/views/shipments/show.html.haml
.row
  .col-xs-12
    %h1
      Shipment ID
      = @shipment.id

.row
  .col-xs-12
    %table.table.table-striped
      %tbody
        %tr
          %th
            Hospital number
          %td
            = @shipment.hospital_number
        %tr
          %th
            Objective code
          %td
            = @shipment.objective_code

        - if @shipment.organism.present?
          %tr
            %th
              Organism
            %td
              = @shipment.organism

        %tr
          %th
            Isolate starting number
          %td
            = @shipment.starting_number
        %tr
          %th
            Isolate quantity to expect
          %td
            = @shipment.isolate_quantity
        %tr
          %th
            Created at
          %td
            = full_date_format @shipment.created_at
        %tr
          %th
            Updated at
          %td
            = full_date_format @shipment.updated_at

.row
  .col-xs-12
    = link_to "Start data entry", data_entry_shipment_path(@shipment), class: "btn btn-primary"